### ISSUE TITLE
Building with AdaEngineEmbeddable

### ISSUE THREAD

**Issue by martintc** [AdaEngine/AdaEngine#33]
When starting a new project and adding AdaEngine as a dependency, it prompts for 3 packages; AdaEngine, AdaEngineEmbeddable, and AdaEditor. 

![Screenshot](https://github.com/AdaEngine/AdaEngine/assets/33560895/696286e7-7e16-4b54-863c-7fa853473922)

If I keep AdaEngineEmbeddable, when building I get the following errors.

![Screenshot](https://github.com/AdaEngine/AdaEngine/assets/33560895/62289db3-1f99-489c-878a-1638b3c7d026)

**Comment by WeDontNeedTo** [comment]
Hi! @SpectralDragon @martintc , plz check this PR for fix https://github.com/AdaEngine/AdaEngine/pull/35

**Comment by SpectralDragon** [comment]
> Hi! @SpectralDragon @martintc , plz check this PR for fix https://github.com/AdaEngine/AdaEngine/pull/35

Thanks for your job! Great PR
